# Generated by Django 4.2.5 on 2023-12-28 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video_url',
            field=models.URLField(blank=True, help_text='Enter the URL of the video.', null=True),
        ),
    ]
